nome = input('Digite algo...')

print('Decimal...')
print(nome.isdecimal())
print('Alfa...')
print(nome.isalpha())
print('Número...')
print(nome.isnumeric())
print('Sé todas as letras são minúsculas...')
print(nome.islower())
print('Alfa númericos..')
print(nome.isalnum())
print('Sé o idioma atual...')
print(nome.isascii())
print('Sé so tem números númericos...')
print(nome.isdigit())
print('Identificador...')
print(nome.isidentifier())
print('Caracteres imprimiveis...')
print(nome.isprintable())
print('Espaço em branco...')
print(nome.isspace())
print('Maiúsculas...')
print(nome.isupper())